### ISSUE TITLE
How to publish to trusted testers exactly ?

### ISSUE THREAD

**Issue by flazouh** [fregante/chrome-webstore-upload-cli#79]
Hi, I see this parameter --trusted-testers for the publish command, but what if I want to upload it, and then publish to trusted testers ?

my current config:

```yaml
      - name: Upload to Chrome Web Store
#        run: npx chrome-webstore-upload-cli@3.0.0 upload --source chrome-extension-${{ github.sha }}.zip --auto-publish
        run: npx chrome-webstore-upload-cli@3.0.0 publish --source chrome-extension-${{ github.sha }}.zip --trusted-testers
        env:
          EXTENSION_ID: hbghjfaenddmdpbkobgdcgkmcdcdjjko
          CLIENT_ID: ${{ secrets.CLIENT }}
          CLIENT_SECRET: ${{ secrets.SECRET }}
          REFRESH_TOKEN: ${{ secrets.TOKEN }}
      - name: Delete artifact
        uses: GeekyEggo/delete-artifact@v4.1.0
        with:
          name: chrome-extension-${{ github.sha }}.zip
```
          
I was using upload with --auto-publish to do the job, but I've reached a point where I need to test the extension before making it live for my users.
